version: 2
sources:
  - name: central_raw_mdharura
    database: postgres
    schema: central_raw_mdharura
    tables:
      - name: tasks
        description: This table contains raw data for signals reported via M-dharura app
      - name: roles
        description: This table contains raw data for user roles on M-dharura app
      - name: units
        description: This table contains raw data for community, health facility, subcounty, county units on M-dharura app
  - name: staging
    database: postgres
    schema: mdharura_dbt_staging
    tables:
      - name: stg_roles
        description: This table normalized data for user roles on M-dharura app
      - name: stg_units
        description: This table normalized data for community, health facility, subcounty, county units on M-dharura app
      - name: stg_tasks
        description: This table normalized data for signals reported via M-dharura app
