{{
    config(
        post_hook=[
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_date ON {{this}} USING btree ("DATE");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_epiweek ON {{this}} USING btree ("EPI_WEEK");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_year ON {{this}} USING btree ("YEAR");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_county ON {{this}} USING btree ("COUNTY");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_subcounty ON {{this}} USING btree ("SUB_COUNTY");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_unit_name ON {{this}} USING btree ("UNIT_NAME");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_unit_id ON {{this}} USING btree ("UNIT_ID");',
            'CREATE INDEX IF NOT EXISTS idx_rpt_agg_indicators_unit_type ON {{this}} USING btree ("UNIT_TYPE");',
        ]
    )
}}

select
    coalesce(a."DATE", b."DATE") as "DATE",
    coalesce(a."EPI_WEEK", b."EPI_WEEK") as "EPI_WEEK",
    coalesce(a."YEAR", b."YEAR") as "YEAR",
    coalesce(a."COUNTY", b."COUNTY") as "COUNTY",
    coalesce(a."COUNTY_ID", b."COUNTY_ID") as "COUNTY_ID",
    coalesce(a."COUNTY_UID", b."COUNTY_UID") as "COUNTY_UID",
    coalesce(a."COUNTY_CODE", b."COUNTY_CODE") as "COUNTY_CODE",
    coalesce(a."SUB_COUNTY", b."SUB_COUNTY") as "SUB_COUNTY",
    coalesce(a."SUB_COUNTY_ID", b."SUB_COUNTY_ID") as "SUB_COUNTY_ID",
    coalesce(a."SUB_COUNTY_UID", b."SUB_COUNTY_UID") as "SUB_COUNTY_UID",
    coalesce(a."SUB_COUNTY_CODE", b."SUB_COUNTY_CODE") as "SUB_COUNTY_CODE",
    coalesce(a."UNIT_NAME", b."UNIT_NAME") as "UNIT_NAME",
    coalesce(a."UNIT_TYPE", b."UNIT_TYPE") as "UNIT_TYPE",
    coalesce(a."UNIT_UID", b."UNIT_UID") as "UNIT_UID",
    coalesce(a."UNIT_ID", b."UNIT_ID") as "UNIT_ID",
    coalesce(a."UNIT_CODE", b."UNIT_CODE") as "UNIT_CODE",
    -- Table A specific columns
    a."SIGNALS_REPORTED",
    a."SIGNALS_VERIFIED",
    a."SIGNALS_VERIFIED_TRUE",
    a."SIGNALS_RISK_ASSESSED",
    a."SIGNALS_RESPONDED",
    a."SIGNALS_TO_BE_ESCALATED",
    a."SIGNALS_ESCALATED",
    a."CEBS_SIGNALS_REPORTED",
    a."CEBS_SIGNALS_VERIFIED",
    a."CEBS_SIGNALS_VERIFIED_TRUE",
    a."CEBS_SIGNALS_RISK_ASSESSED",
    a."CEBS_SIGNALS_RESPONDED",
    a."CEBS_SIGNALS_TO_BE_ESCALATED",
    a."CEBS_SIGNALS_ESCALATED",
    a."HEBS_SIGNALS_REPORTED",
    a."HEBS_SIGNALS_VERIFIED",
    a."HEBS_SIGNALS_VERIFIED_TRUE",
    a."HEBS_SIGNALS_RISK_ASSESSED",
    a."HEBS_SIGNALS_RESPONDED",
    a."HEBS_SIGNALS_TO_BE_ESCALATED",
    a."HEBS_SIGNALS_ESCALATED",
    a."VEBS_SIGNALS_REPORTED",
    a."VEBS_SIGNALS_VERIFIED",
    a."VEBS_SIGNALS_VERIFIED_TRUE",
    a."VEBS_SIGNALS_RISK_ASSESSED",
    a."VEBS_SIGNALS_RESPONDED",
    a."VEBS_SIGNALS_TO_BE_ESCALATED",
    a."VEBS_SIGNALS_ESCALATED",
    a."LEBS_SIGNALS_REPORTED",
    a."LEBS_SIGNALS_VERIFIED",
    a."LEBS_SIGNALS_VERIFIED_TRUE",
    a."LEBS_SIGNALS_RISK_ASSESSED",
    a."LEBS_SIGNALS_RESPONDED",
    a."LEBS_SIGNALS_TO_BE_ESCALATED",
    a."LEBS_SIGNALS_ESCALATED",
    a."SIGNALS_REPORTED_VIA_SMS",
    a."SIGNALS_VERIFIED_VIA_SMS",
    a."SIGNALS_INVESTIGATED_VIA_SMS",
    a."SIGNALS_RESPONDED_VIA_SMS",
    a."SIGNALS_ESCALATED_VIA_SMS",
    a."SIGNALS_SUMMARIZED_VIA_SMS",
    -- Table B specific columns
    b."CHVS_REGISTERED",
    b."CHVS_REPORTING",
    b."CDRS_REGISTERED",
    b."CDRS_REPORTING",
    b."HCWS_REGISTERED",
    b."HCWS_REPORTING",
    b."CHAS_REGISTERED",
    b."CHAS_REPORTING",
    b."CHAS_VERIFYING",
    b."AHAS_REGISTERED",
    b."AHAS_REPORTING",
    b."AHAS_VERIFYING",
    b."SFPS_REGISTERED",
    b."SFPS_REPORTING",
    b."SFPS_VERIFYING",
    b."VIEWERS_REGISTERED",
    b."CEBS_REGISTERED",
    b."CEBS_INVESTIGATING",
    b."CEBS_RESPONDING",
    b."CEBS_ESCALATING",
    b."CEBS_SUMMARIZING",
    b."HEBS_REGISTERED",
    b."HEBS_INVESTIGATING",
    b."HEBS_RESPONDING",
    b."HEBS_ESCALATING",
    b."HEBS_SUMMARIZING",
    b."VEBS_REGISTERED",
    b."VEBS_INVESTIGATING",
    b."VEBS_RESPONDING",
    b."VEBS_ESCALATING",
    b."VEBS_SUMMARIZING"
from {{ ref("aggregate_ebs_tasks_indicators_report") }} a
full join
    {{ ref("aggregate_ebs_roles_indicators_report") }} as b
    on a."DATE" = b."DATE"
    and a."COUNTY" = b."COUNTY"
    and a."SUB_COUNTY" = b."SUB_COUNTY"
    and a."UNIT_ID" = b."UNIT_ID"
